### ISSUE TITLE
[JOSS] Simulations run in the GUI thread ==> freezing GUI

### ISSUE THREAD

**Issue by sidihamady** [cire-thk/BifacialSimu#15]
An issue that I mentioned in the Preview stage: the simulations run in the main GUI thread, which make it unresponsive during long time (even if the spyder console output is seen). Simulations should be run in a working thread using the 'threading' library, and a communication between the two threads can be done, e.g. to show the progress of calculations (like a progessbar in tkinter or a simple label). Using threading will make the GUI part remaining responsive and the simulations can be monitored and even stopped when needed. This makes the user experience much more easier.

[https://github.com/openjournals/joss-reviews/issues/4443#issuecomment-1158667882](https://github.com/openjournals/joss-reviews/issues/4443#issuecomment-1158667882)

**Comment by EwaGomez** [comment]
Thank you for your comment! I will read into the threading library!
Would you mind if I resolve this issue after the JOSS review? Right now I would love to concentrate on more research related issues and later in the year on a more user-friendly design.

**Comment by EwaGomez** [comment]
@sidihamady - You are totally right, the novelty of BifacialSimu was not the GUI, but the albedo and electrical models. I made those changes to the original paper! 

I still like the idea of Threading and I have been working on it for the last few days. I was able to integrate Threading and to make the GUI responsive during simulations, but unfortunately is matplotlib not threadsafe and was not able to communicate with the Thread, where the calculations were running. Matplotlib is a crucial part of BifacialSimu, since, besides the results data, you get 9 interactive plots at the end of the simulation. So I had to delete Threading again to keep Matplotlib running. 
I am now reading into multiprocessing instead of Threading. 
By any chance, do you have any experience in Tkinter, Multiprocessing and Matplotlib?

Do you still think that this is an issue for the JOSS publication?

**Comment by sidihamady** [comment]
Dear @EwaGomez 

To implement the threading you need to understand some important points.
First the GUI (so Tk and matplotlib) runs in the main thread. Tk and matplotlib are not thread safe. And they don't need to be thread safe. The organization is as follows:
1/ the main thread with UI
2/ a working thead, with only calculations and without any direct call to the GUI.
The communication between the threads can be done using various methods, e.g. events, mutex, ... (with a timer for example).
The simplest way is to perform all calculations is a working thread and setup a termination function that can create/update plots. If you try to plot directly from the working thread, the program will not work.
If by design you have mixed UI stuff with the simulation routines, it will take some time to redesign the application. One golden rule is to never mix UI and calculations. Different routines, different classes. It can take some time in the beginning but it is really crucial.
You can look at the application I developed to simulate solar cell I-V characteristic: [https://github.com/sidihamady/Photovoltaic-Model](https://github.com/sidihamady/Photovoltaic-Model).

For JOSS, as I mentioned, if you consider GUI as something new in the publication, then it should follow usability rules, and be always responsive and offers features not offered by a command-line program.
If the novelty is only in albedo and electrical models, then this should be highlghted clearly in the paper, and therefore remove the part relating to the novelty which would be linked to the GUI.

**Comment by EwaGomez** [comment]
Dear @sidihamady,
Thank you for your input! 
I just released a new version of BifacialSimu including threading. The GUI is now responsive during the simulation. But I also implemented your second suggestion and shifted the main USP of the paper from the GUI to the different simulations models, especially the albedo models. In the future, after the JOSS publication, I will implement a timer and a function to update the plots.
